### PR TITLE
Implemented dynamic links scanning

### PR DESCRIPTION
**Pull request by sweoggy**
Fixes https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/24

Also includes some optimisations to the ordinary scanning, extended test case for DOM changes and relevant link tooltip.

### CODE REVIEW

**Comment by feinstaub** [comment]
Thanks for the work. Please rebase on latest master without the merge commit 590e9c0f4693bda321737bb9c5627ab7dee6edca and request again. Also consider adding yourself to the CONTRIBUTORS file in a separate commit

**Comment by feinstaub** [comment]
I tried the new test page. The new scanning method works fine on openSUSE Firefox 38.0.1

**Comment by sweoggy** [comment]
@feinstaub I am having some problem with rebasing my fork onto the latest master. I always end up with diverging branches which I can't commit nor complete merge. Could you please help me out?

**Comment by feinstaub** [comment]
@sweoggy I tried myself but did not succeed either. It would have required some interactive rebase tricks and some patience. So instead, I merged your branch as is into master. Please make sure next time to base each feature on the latest master.

**Comment by feinstaub** [comment]
So now happy hacking. :)

**Comment by sweoggy** [comment]
Great, thanks! Still new to GIT, lesson learned hopefully :)

**Comment by feinstaub** [comment]
@sweoggy: as for git client software: with GitExtensions you can do some nice fine-grained rebase operations via GUI:
shot1

**Comment by sweoggy** [comment]
@feinstaub thanks for the tip, have installed and will try it out when needed. Tried rebasing with git bash before

**Pull request closed without merging**
