### PR TITLE
changed innerHTML to jsonToDOM,

### LINKED ISSUE #46: 0.99.41c review security issue
Hi,

we have one last review issue that must be fixed before that addon is ready to be published on AMO (Addons/Mozilla). These are the technical details of the review comment:

"You have a grave outstanding issue. Version 0.99.37 was mistakenly approved, it should not have been. I sincerely apologize.

A. The outstanding issue is on and around hyperlink-scanner.js#L235

outerElement.innerHTML = outerElement.innerHTML.insert(endLinkPos, alienHrefText);

We do not allow this innerHTML, it is a vulnerability hackers are taking advantage of.

Please update this to use createTextNode and creatEelement. You may find the jsonToDOM function here helpful for this - https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/DOM_Building_and_HTML_Insertion#JSON_Templating

This is the only thing that needs fixing, the rest is good."

### PR DESCRIPTION
**Pull request by AWolf81**
This should fix #46 

I've tested it with the local webserver test cases for dynamic content and everything is working like before.

### CODE REVIEW

**Comment by sweoggy** [comment]
There is a slight problem with this change. The folder icon gets appended to the end of the inserted string. See below images:

Current master, e476a76cac4c0de5e678c6a2a38c02282214b4d0:
Image of master

And with this pull request it looks like below:
image of pull request 47

**Comment by AWolf81** [comment]
OK, fixed the issue and used `innerHTML` again. So position is as before. But I'm not sure if it's OK because we're still using `innerHTML` but with jsonToDOM. How can I test the js injection for the mentioned security hole?

**Comment by AWolf81** [comment]
accidentially closed.

**Comment by AWolf81** [comment]
@feinstaub I've create a similar addon like yours with some parts forked from your repo. It would be great if you could have a look at it. I've first thought that I could create a pull request to your repo but it's too different and I'm not sure how to proceed. What do you think? Should I publish it to mozilla addon gallery or could we merge it to your repository?

My repository https://github.com/AWolf81/firefox_addon_local_links is created from scratch and it's probably hard to merge to your repo. But a merge would be possible.

The plugin is working pretty well with more features added (e.g. whitelist option, right click to reveal the containing folder from a file link instead of opening the file directly & icon disable option). At the moment, I'm trying to add samba share links in the devel branch so links like 'smb://servername/share' can be opened with Linux. 

But that's not working yet, I've created a Stackoverflow question for this to try to get some help but no response yet. (see here http://stackoverflow.com/questions/34612440/how-to-open-samba-share-in-firefox-plugin). Maybe I'm checking if I can get some help at the IRC channel from mozilla.

**Comment by feinstaub** [comment]
Hi @AWolf81,

first of all sorry for having missed your comment 8 days ago. I am rather busy right now.

Great to hear that you created a similar addon by using some of this addon's code. Since you say that your addon does essentially the same as my original work I think it would be best to have only one in the end.

In this repository, there is this blocking issues before the next review can be done:

- https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/46

I sadly have no time to review or test it. But I just made you a collaborator. So you could merge it on your own. The same way you could the other features of your current addon. You could give me a signal when everything is ready and I will build it and put to AMO review. This would save you some admin work but there might be some time-delay on my side.

If you don't like the waiting and feel better to manage the AMO stuff yourself you are free to publish your work as separate addon. In this case, I would be happy if there will remain fair credits to this addon.

**Comment by AWolf81** [comment]
No problem for late response and thanks for adding as collaborator. I've added my addon code into a branch see PR #50. I've added my code because I also think that it is better to have only one plugin in mozilla addon gallery.

It's a lot of stuff in the other PR because I've cleaned and changed a lot.

We can close this PR with-out merging because it's not needed with my code. There I'm only adding the icon behind the links so there shouldn't be an issue with inserting scripts into the page.

**Pull request closed without merging**
