### PR TITLE
Fix issue 74 - icon performance improvement

### PR DESCRIPTION
**Pull request by AWolf81**
This fix improves the icon addition with many file links on a single page as reported in issue #74.

I've created a test page with 800 links (400 not shown at start). The hidden links were just for testing. Addon is still adding the icon to invisible file links.

Disabling the addition for invisible icons on load is possible but adding the icon once the links are displayed is pretty complicated because there is no event for it. So another observer would be required to watch the display change and add the icon then.

That's why I decided to check if a performance improvement is possible and now the icon is visible after one second instead of ~45s. Also FF was almost crashing before this fix. Now FF has still a framerate drop to 0 FPS but that was only visible with the performace monitor in console.
Parsing html is taking that time (see screenshot below) but I'm not sure why because each parse takes only 0,01ms and that shouldn't delay it that much.
screenshot performance

@feinstaub Please review this later. I think we first need to finalize the other two PRs before we're closing this. This fix is for the next release after 0.99.45-1. Can you please add a milestone for the next release, so we can mark the issue correctly?

### CODE REVIEW

**Comment by feinstaub** [comment]
We have now three milestones:

0.99.45: upcoming release
0.99.47: next release
0.99.48: some future release

**Comment by AWolf81** [comment]
@feinstaub I think we can release the version tagged with 0.99.45-1 to Mozilla gallery.

I've tested this version with
FF nightly 52.0a1 (2016-09-30) (64-bit) Windows
and FF 51.0a2 developer edition.  It's working as expected.
 
I couldn't test it with FF 49.0.1 because I can't install the addon if it is not signed and I couldn't find a portable developer version with this version (Disabling signing with xpinstall in about:config isn't working in normal FF versions anymore, only Developer edition is allowing it.)

Could you please also update the screenshots in Mozilla Gallery because they're pretty out-dated? You can take the screenshots from master ([doc/screenshots](https://github.com/feinstaub/firefox_addon_local_filesystem_links/tree/master/doc/screenshots)). (Maybe you could create another one for the addons settings.)

Can you please post-pone the due dates for the milestones 0.99.47 & 0.99.48? They're red because they're over the due date.

How about the two open PRs? Are there any issues that I've missed?

**Comment by feinstaub** [comment]
Thanks for summarizing the current issues. I agree to release. I try to do it this week. Then I also say something to the other questions.

**Comment by feinstaub** [comment]
(I cannot promise this week)

**Comment by AWolf81** [comment]
@feinstaub 
Can you please add the version 0.99.45-1 to mozilla gallery? (I haven't re-tested the addon today but it will still work because my current stable FF version 50.x is older than the nightly that I've tested last year in October)

Last update is pretty old and I think the new features with 0.99.45-1 (see [changelog](https://github.com/feinstaub/firefox_addon_local_filesystem_links/blob/master/CHANGELOG)) are really useful (addon-bar icon & improved link scanning) 
The -1 in the tag is for the bugfix of false exe trigger for executable directories in linux (see #72)

I'd like to open a project so we can keep track of open issues. Is that OK? I haven't used that before but I think that would help to track of everything.

**Comment by feinstaub** [comment]
@AWolf81: Thanks for reminding me again and your patience. I am so sorry that I couldn't find the time up to now. My backlog is still too big. :(

To see forward:

1) I cannot release something to AMO that I built myself and have not tested it at least a bit. I did that before and the result was a buggy version. So, I would need some time en block to test and do the release. And I cannot give you a proper time estimation.

2) Suggestion 1 - short-term: you put everything together (compiled addon that worked on your machine, with proper version number, changelog from current to this version) and send it to me so that I only have to upload this to AMO and fill in the forms. Then it is only "paperwork" for me which I can do without much concentration.

3) Suggestion 2 - long-term, if you are not happy with suggestion 1: I am willing to give up AMO ownership if it helps the project. How can we exchange email addresses to not having to communicate only via public github?

> I'd like to open a project so we can keep track of open issues. Is that OK? I haven't used that before but I think that would help to track of everything.

I am not familiar with "projects". What is it? But I would say if you think it helps, please go ahead (and tell me what are the advantages).

**Comment by AWolf81** [comment]
@feinstaub 
No problem.

Suggestion 1 is OK and I'll create everything. Can you please send me the API Key & secret so I can create a signed XPI as mentioned [here](https://blog.mozilla.org/addons/2015/12/18/signing-firefox-add-ons-with-jpm-sign/).

Also suggestion 2 would be great, so I could directly update the next version but we can do that once you're having more time again.
My e-mail address is awolf2904 at gmail dot com

OK, I'll create a project and then we can check if it helps.

For future releases I have to check if we can change the addon to a WebExtension as `jpm` will be deprecated soon but I think this will be a pretty large change.

**Pull request merged**
