### PR TITLE
Merge remote local addon

### PR DESCRIPTION
**Pull request by AWolf81**
OK, I've added this branch to implement the repository that I've created [here](https://github.com/AWolf81/firefox_addon_local_links).

Unit tests are passing and the addon is working in Windows 8.1 and should also work in Ubuntu (not tested again). Just the whitelist test for the pageMod include is not added yet. I need to check how to write it.

I hope I've done no mistake at resolving the merge conflicts but it should be OK. Any way, please have a look at it and do some tests.

Just the smb link feature is missing and I have to check how I can add it.

### CODE REVIEW

**Comment by feinstaub** [comment]
Hi, I tried out the new code. I found some issues which I will post later but in general it seems to work fine. Thanks for your work. You can merge it to master now.

**Comment by feinstaub** [comment]
**Issue 1:**
When I click a link I see some console output:
```
console.log: alien-local-filesystem-links: clicked file link: file:////tmp/
console.log: alien-local-filesystem-links: before replace file:////tmp/
console.log: alien-local-filesystem-links: replaced file://///tmp/
```
Before I send this to AMO  any debugging output needs to be removed (comment out).

**Comment by feinstaub** [comment]
**Minor issue 2:**
I like it that you put screenshots to the README.md. Instead of having them on a hosting site you can put them here: doc/screenshots/

**Comment by feinstaub** [comment]
**Minor issue 3:**
In the addon preferences the option "Enable link icons" does not work for me. The "How many?" option I don't understand.

**Comment by AWolf81** [comment]
Hi,

OK, noticed and thanks for checking. I've missed these issues.

I'll add the screenshots to that folder and remove debugging logs.

I'll also check the enable icon option. For me it worked after reloading
the test page.

The 'how many' can be removed.  It's just from a demo and not needed. I
remove it once I am at my laptop.

Best regards,
Alexander.
Am 28.02.2016 12:13 schrieb "feinstaub" <notifications@github.com>:

**Pull request merged**
