### PR TITLE
Fixes issue #57

### PR DESCRIPTION
**Pull request by AWolf81**
This branch will fix issue #57.

I've changed the link selector in the content script to match every link that's starting with `file:`

Windows was easier to implement because `file:\\` or `file://` are working as expected with-out any change except the selector.

In Ubuntu 14.04.3 it required to fix the url before opening because FF is adding three slashes in front of the backslashes and it required to replace the backslashes with slashes.

I've added a button to the standard test case to easily switch between the backslash style which some websites are using and the correct syntax with slashes.

I checked every link in the standard test case and it is working in Windows 8.1 and Ubuntu 14.04.3 with FF 44.0.2.

Also jQuery for the test cases moved in a common folder so we can use the same file in multiple test pages.

### CODE REVIEW

**Comment by AWolf81** [comment]
I think the idea to add a log is good but the problem is that it won't show in the browser console because it's in the addon code. (A normal log will only show-up during plugin development.)
And bringing it to the browser console requires some coding.

I would keep it as is because it works. If there are any issues with it we can add the preference to disable it by default.

**Comment by feinstaub** [comment]
Log message:
I wouldn't mind if the log message would only be printed during development. You could add a comment about what you said: that it would be nicer to show it to the user but that it requires some more work.

> I would keep it as is because it works. If there are any issues with it we can add the preference to disable it by default.

You did all the coding work, so you can decide on that for this PR. My point is that I think that non-standard-conforming websites are a bad thing. And I don't like to silently support this by not telling the user or make the user perform a willful action (like enabling the option).

**Comment by AWolf81** [comment]
OK, I'll add a comment at the backslash handling code and a `console.log` to have a reminder. So we could later add a better handling for this.

**Comment by AWolf81** [comment]
I've checked if we could add a preference to do an enable for non-standard links like `file:\\c:\` but I needed to do a test in launch-local-process start function and firefox replaced the backslashes after a click on the link with slashes. So adding a preference seems not possible at the moment.

But on the icon click I have to add the backslash handling code because it's a span tag and not an a-tag so FF won't fix the path here.

**Pull request merged**
