### PR TITLE
Improved .jpmignore

### PR DESCRIPTION
**Pull request by sweoggy**
- Improved .gitignore, added files which are automatically generated by
running "jpm xpi"

As discussed in https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/37

### CODE REVIEW

**Comment by sweoggy** [comment]
@feinstaub this might help the addon getting approved

**Comment by sweoggy** [comment]
@feinstaub So are we ready to merge this?

**Comment by feinstaub** [comment]
I now uploaded the xpi generated from your branch as 0.99.39b to AMO. Let's wait for the response by the AMO editors before merging it.

**Comment by sweoggy** [comment]
Sounds good!

**Comment by sweoggy** [comment]
@feinstaub any news from AMO?

**Comment by feinstaub** [comment]
Queue Position: 71 of 109 (queues are not reviewed strictly in order)

**Comment by feinstaub** [comment]
Because the review is taken longer than normal, I would say you can go ahead: merge this branch and tag it "0.99.39b".

**Pull request merged**
