### PR TITLE
Firefox 39+ compatibility fixes

### PR DESCRIPTION
**Pull request by sweoggy**
Fixes compatibility in Firefox 39+. Drawback? I don't think disabling scanner works anymore. This is caused by a bug in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1189781.

Also see discussion in https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/37

- Some fixes to conform with the strict JavaScript standard.

- Some other small fixes

### CODE REVIEW

**Comment by sweoggy** [comment]
@feinstaub any comment before merging?

**Comment by feinstaub** [comment]
Thanks for your investigations and coding.

> Drawback? I don't think disabling scanner works anymore.

Disabling the scanner can be fixed at a later time.

**Comment by feinstaub** [comment]
Tested on my FF 39 on openSUSE => Works again! Great! :-)

I don't see the brown folder icon anymore, do you? In any case, please merge.

**Comment by feinstaub** [comment]
(I just did the merge myself)

**Comment by sweoggy** [comment]
> Coding style: in http://www.w3schools.com/js/js_conventions.asp there is no space between the function and its parameter list. We should adhere to it.

I will fix that tomorrow :) Wasn't the folder icon removed in https://github.com/feinstaub/firefox_addon_local_filesystem_links/commit/bdef48140cc2a5106a4f9302fe9fdd733a8c743c?

Should we remove the "Exlude 'Start with' URIs...", since I believe it is not relevant for the time being?

**Comment by feinstaub** [comment]
> I will fix that tomorrow :)

thx.

> Wasn't the folder icon removed in bdef481?

oh yes, you are right.

Should we remove the "Exlude 'Start with' URIs...", since I believe it is not relevant for the time being?

It is still working for me. Doesn't it for you?
Some users need it to exclude complex websites that would be too slow otherwise.
Later, the user should be able to also exclude a page via context menu or/and give the possibility to prevent scanning for all pages except for white-listed ones which is probably safer considering this https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/16)

**Pull request merged**
