### PR TITLE
JPM compatibility fixes

### PR DESCRIPTION
**Pull request by sweoggy**
- Made tests JPM compatible
- New, more convenient and JPM compatible, Windows batch file
- Shamelessly added myself to contributors

### CODE REVIEW

**Comment by feinstaub** [comment]
Thanks for the work. I'll test it as soon as possible.

**Comment by feinstaub** [comment]
I retested jpm on my openSUSE machine which now works, see https://github.com/mozilla/jpm/issues/287#issuecomment-123475529 (your PR is unrelated to that but still good news)

Please fix above-mentioned in-code issue before I merge.

**Comment by feinstaub** [comment]
I just added you as "Collaborator" to this repository. So you can then try to merge the pull request yourself.

**Comment by sweoggy** [comment]
@feinstaub thanks!

**Pull request merged**
